
// This file has been generated by the GUI designer. Do not modify.
namespace Launchpad.LauncherUtil
{
	public partial class GameUpload_Upload
	{
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Launchpad.LauncherUtil.GameUploadWidget_Upload
			global::Stetic.BinContainer.Attach (this);
			this.Name = "Launchpad.LauncherUtil.GameUpload_Upload";
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
