
// This file has been generated by the GUI designer. Do not modify.
namespace Launchpad.LauncherUtil
{
	public partial class WizardPageWidget
	{
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Launchpad.LauncherUtil.WizardPageWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "Launchpad.LauncherUtil.WizardPageWidget";
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
