
// This file has been generated by the GUI designer. Do not modify.
namespace Launchpad.LauncherUtil
{
	public partial class EditProfileDialog
	{
		private global::Gtk.VBox vbox5;
		private global::Gtk.VBox vbox6;
		private global::Gtk.Alignment alignment5;
		private global::Gtk.Label label2;
		private global::Gtk.HSeparator hseparator2;
		private global::Gtk.HBox hbox4;
		private global::Gtk.Alignment alignment2;
		private global::Gtk.Label profileNameLabel;
		private global::Gtk.Alignment alignment3;
		private global::Gtk.Entry profileNameEntry;
		private global::Gtk.HSeparator hseparator1;
		private global::Gtk.Alignment alignment6;
		private global::Gtk.Label label3;
		private global::Gtk.VBox vbox7;
		private global::Gtk.HBox hbox6;
		private global::Gtk.Alignment alignment7;
		private global::Gtk.Label label4;
		private global::Gtk.Alignment alignment8;
		private global::Gtk.Entry FTPURLEntry;
		private global::Gtk.HBox hbox7;
		private global::Gtk.Alignment alignment10;
		private global::Gtk.Label label5;
		private global::Gtk.Alignment alignment9;
		private global::Gtk.Entry FTPUsernameEntry;
		private global::Gtk.HBox hbox8;
		private global::Gtk.Alignment alignment11;
		private global::Gtk.Label label6;
		private global::Gtk.Alignment alignment12;
		private global::Gtk.Entry FTPPasswordEntry;
		private global::Gtk.VBox vbox8;
		private global::Gtk.HSeparator hseparator3;
		private global::Gtk.Alignment alignment13;
		private global::Gtk.Label label7;
		private global::Gtk.HSeparator hseparator4;
		private global::Gtk.HBox hbox9;
		private global::Gtk.Alignment alignment14;
		private global::Gtk.Label label8;
		private global::Gtk.Alignment alignment18;
		private global::Gtk.Entry gameNameEntry;
		private global::Gtk.HBox hbox10;
		private global::Gtk.Alignment alignment15;
		private global::Gtk.Label gamePathChooserLabel;
		private global::Gtk.Alignment alignment19;
		private global::Gtk.FileChooserButton gamePathChooser;
		private global::Gtk.HBox hbox11;
		private global::Gtk.Alignment alignment16;
		private global::Gtk.Label label10;
		private global::Gtk.Alignment alignment20;
		private global::Gtk.Entry gameVersionEntry;
		private global::Gtk.HBox hbox12;
		private global::Gtk.Alignment alignment17;
		private global::Gtk.Label label11;
		private global::Gtk.Alignment alignment21;
		private global::Gtk.ComboBox systemTargetSelector;
		private global::Gtk.Button buttonCancel;
		private global::Gtk.Button buttonOk;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Launchpad.LauncherUtil.EditProfileDialog
			this.Name = "Launchpad.LauncherUtil.EditProfileDialog";
			this.Title = global::Mono.Unix.Catalog.GetString ("Create or Edit Profile");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.Resizable = false;
			this.DefaultWidth = 450;
			this.DefaultHeight = 600;
			// Internal child Launchpad.LauncherUtil.EditProfileDialog.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.vbox5 = new global::Gtk.VBox ();
			this.vbox5.Name = "vbox5";
			this.vbox5.Spacing = 6;
			// Container child vbox5.Gtk.Box+BoxChild
			this.vbox6 = new global::Gtk.VBox ();
			this.vbox6.Name = "vbox6";
			this.vbox6.Spacing = 6;
			// Container child vbox6.Gtk.Box+BoxChild
			this.alignment5 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment5.Name = "alignment5";
			// Container child alignment5.Gtk.Container+ContainerChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Profile Settings");
			this.alignment5.Add (this.label2);
			this.vbox6.Add (this.alignment5);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.alignment5]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.hseparator2 = new global::Gtk.HSeparator ();
			this.hseparator2.Name = "hseparator2";
			this.vbox6.Add (this.hseparator2);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.hseparator2]));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox ();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.alignment2 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment2.Name = "alignment2";
			// Container child alignment2.Gtk.Container+ContainerChild
			this.profileNameLabel = new global::Gtk.Label ();
			this.profileNameLabel.Name = "profileNameLabel";
			this.profileNameLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Profile Name:");
			this.alignment2.Add (this.profileNameLabel);
			this.hbox4.Add (this.alignment2);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.alignment2]));
			w6.Position = 0;
			w6.Expand = false;
			w6.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.alignment3 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment3.Name = "alignment3";
			this.alignment3.LeftPadding = ((uint)(64));
			// Container child alignment3.Gtk.Container+ContainerChild
			this.profileNameEntry = new global::Gtk.Entry ();
			this.profileNameEntry.CanFocus = true;
			this.profileNameEntry.Name = "profileNameEntry";
			this.profileNameEntry.Text = global::Mono.Unix.Catalog.GetString ("Example Profile");
			this.profileNameEntry.IsEditable = true;
			this.profileNameEntry.InvisibleChar = '●';
			this.alignment3.Add (this.profileNameEntry);
			this.hbox4.Add (this.alignment3);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.alignment3]));
			w8.Position = 1;
			this.vbox6.Add (this.hbox4);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.hbox4]));
			w9.Position = 2;
			w9.Expand = false;
			w9.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.hseparator1 = new global::Gtk.HSeparator ();
			this.hseparator1.Name = "hseparator1";
			this.vbox6.Add (this.hseparator1);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.hseparator1]));
			w10.Position = 3;
			w10.Expand = false;
			w10.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.alignment6 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment6.Name = "alignment6";
			// Container child alignment6.Gtk.Container+ContainerChild
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Remote Connection Settings");
			this.alignment6.Add (this.label3);
			this.vbox6.Add (this.alignment6);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.alignment6]));
			w12.Position = 4;
			w12.Expand = false;
			w12.Fill = false;
			this.vbox5.Add (this.vbox6);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.vbox6]));
			w13.Position = 0;
			w13.Expand = false;
			w13.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.vbox7 = new global::Gtk.VBox ();
			this.vbox7.Name = "vbox7";
			this.vbox7.Spacing = 6;
			// Container child vbox7.Gtk.Box+BoxChild
			this.hbox6 = new global::Gtk.HBox ();
			this.hbox6.Name = "hbox6";
			this.hbox6.Spacing = 6;
			// Container child hbox6.Gtk.Box+BoxChild
			this.alignment7 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment7.Name = "alignment7";
			// Container child alignment7.Gtk.Container+ContainerChild
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("FTP Connection URL: ");
			this.alignment7.Add (this.label4);
			this.hbox6.Add (this.alignment7);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.alignment7]));
			w15.Position = 0;
			w15.Expand = false;
			w15.Fill = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.alignment8 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment8.Name = "alignment8";
			this.alignment8.LeftPadding = ((uint)(25));
			// Container child alignment8.Gtk.Container+ContainerChild
			this.FTPURLEntry = new global::Gtk.Entry ();
			this.FTPURLEntry.CanFocus = true;
			this.FTPURLEntry.Name = "FTPURLEntry";
			this.FTPURLEntry.Text = global::Mono.Unix.Catalog.GetString ("ftp://example.example.com");
			this.FTPURLEntry.IsEditable = true;
			this.FTPURLEntry.InvisibleChar = '●';
			this.alignment8.Add (this.FTPURLEntry);
			this.hbox6.Add (this.alignment8);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.alignment8]));
			w17.Position = 1;
			this.vbox7.Add (this.hbox6);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.hbox6]));
			w18.Position = 0;
			w18.Expand = false;
			w18.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.hbox7 = new global::Gtk.HBox ();
			this.hbox7.Name = "hbox7";
			this.hbox7.Spacing = 6;
			// Container child hbox7.Gtk.Box+BoxChild
			this.alignment10 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment10.Name = "alignment10";
			// Container child alignment10.Gtk.Container+ContainerChild
			this.label5 = new global::Gtk.Label ();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("FTP Username: ");
			this.alignment10.Add (this.label5);
			this.hbox7.Add (this.alignment10);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.alignment10]));
			w20.Position = 0;
			w20.Expand = false;
			w20.Fill = false;
			// Container child hbox7.Gtk.Box+BoxChild
			this.alignment9 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment9.Name = "alignment9";
			this.alignment9.LeftPadding = ((uint)(54));
			// Container child alignment9.Gtk.Container+ContainerChild
			this.FTPUsernameEntry = new global::Gtk.Entry ();
			this.FTPUsernameEntry.CanFocus = true;
			this.FTPUsernameEntry.Name = "FTPUsernameEntry";
			this.FTPUsernameEntry.Text = global::Mono.Unix.Catalog.GetString ("anonymous");
			this.FTPUsernameEntry.IsEditable = true;
			this.FTPUsernameEntry.InvisibleChar = '●';
			this.alignment9.Add (this.FTPUsernameEntry);
			this.hbox7.Add (this.alignment9);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.alignment9]));
			w22.Position = 1;
			this.vbox7.Add (this.hbox7);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.hbox7]));
			w23.Position = 1;
			w23.Expand = false;
			w23.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.hbox8 = new global::Gtk.HBox ();
			this.hbox8.Name = "hbox8";
			this.hbox8.Spacing = 6;
			// Container child hbox8.Gtk.Box+BoxChild
			this.alignment11 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment11.Name = "alignment11";
			// Container child alignment11.Gtk.Container+ContainerChild
			this.label6 = new global::Gtk.Label ();
			this.label6.Name = "label6";
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("FTP Password: ");
			this.alignment11.Add (this.label6);
			this.hbox8.Add (this.alignment11);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.alignment11]));
			w25.Position = 0;
			w25.Expand = false;
			w25.Fill = false;
			// Container child hbox8.Gtk.Box+BoxChild
			this.alignment12 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment12.Name = "alignment12";
			this.alignment12.LeftPadding = ((uint)(58));
			// Container child alignment12.Gtk.Container+ContainerChild
			this.FTPPasswordEntry = new global::Gtk.Entry ();
			this.FTPPasswordEntry.CanFocus = true;
			this.FTPPasswordEntry.Name = "FTPPasswordEntry";
			this.FTPPasswordEntry.Text = global::Mono.Unix.Catalog.GetString ("anonymous");
			this.FTPPasswordEntry.IsEditable = true;
			this.FTPPasswordEntry.InvisibleChar = '●';
			this.alignment12.Add (this.FTPPasswordEntry);
			this.hbox8.Add (this.alignment12);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.alignment12]));
			w27.Position = 1;
			this.vbox7.Add (this.hbox8);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.hbox8]));
			w28.Position = 2;
			w28.Expand = false;
			w28.Fill = false;
			this.vbox5.Add (this.vbox7);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.vbox7]));
			w29.Position = 1;
			w29.Expand = false;
			w29.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.vbox8 = new global::Gtk.VBox ();
			this.vbox8.Name = "vbox8";
			this.vbox8.Spacing = 6;
			// Container child vbox8.Gtk.Box+BoxChild
			this.hseparator3 = new global::Gtk.HSeparator ();
			this.hseparator3.Name = "hseparator3";
			this.vbox8.Add (this.hseparator3);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.hseparator3]));
			w30.Position = 0;
			w30.Expand = false;
			w30.Fill = false;
			// Container child vbox8.Gtk.Box+BoxChild
			this.alignment13 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment13.Name = "alignment13";
			// Container child alignment13.Gtk.Container+ContainerChild
			this.label7 = new global::Gtk.Label ();
			this.label7.Name = "label7";
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("Game Settings");
			this.alignment13.Add (this.label7);
			this.vbox8.Add (this.alignment13);
			global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.alignment13]));
			w32.Position = 1;
			w32.Expand = false;
			w32.Fill = false;
			// Container child vbox8.Gtk.Box+BoxChild
			this.hseparator4 = new global::Gtk.HSeparator ();
			this.hseparator4.Name = "hseparator4";
			this.vbox8.Add (this.hseparator4);
			global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.hseparator4]));
			w33.Position = 2;
			w33.Expand = false;
			w33.Fill = false;
			// Container child vbox8.Gtk.Box+BoxChild
			this.hbox9 = new global::Gtk.HBox ();
			this.hbox9.Name = "hbox9";
			this.hbox9.Spacing = 6;
			// Container child hbox9.Gtk.Box+BoxChild
			this.alignment14 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment14.Name = "alignment14";
			// Container child alignment14.Gtk.Container+ContainerChild
			this.label8 = new global::Gtk.Label ();
			this.label8.Name = "label8";
			this.label8.LabelProp = global::Mono.Unix.Catalog.GetString ("Game Name: ");
			this.alignment14.Add (this.label8);
			this.hbox9.Add (this.alignment14);
			global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.alignment14]));
			w35.Position = 0;
			w35.Expand = false;
			w35.Fill = false;
			// Container child hbox9.Gtk.Box+BoxChild
			this.alignment18 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment18.Name = "alignment18";
			this.alignment18.LeftPadding = ((uint)(66));
			// Container child alignment18.Gtk.Container+ContainerChild
			this.gameNameEntry = new global::Gtk.Entry ();
			this.gameNameEntry.CanFocus = true;
			this.gameNameEntry.Name = "gameNameEntry";
			this.gameNameEntry.Text = global::Mono.Unix.Catalog.GetString ("LaunchpadExample");
			this.gameNameEntry.IsEditable = true;
			this.gameNameEntry.InvisibleChar = '●';
			this.alignment18.Add (this.gameNameEntry);
			this.hbox9.Add (this.alignment18);
			global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.alignment18]));
			w37.Position = 1;
			this.vbox8.Add (this.hbox9);
			global::Gtk.Box.BoxChild w38 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.hbox9]));
			w38.Position = 3;
			w38.Expand = false;
			w38.Fill = false;
			// Container child vbox8.Gtk.Box+BoxChild
			this.hbox10 = new global::Gtk.HBox ();
			this.hbox10.Name = "hbox10";
			this.hbox10.Spacing = 6;
			// Container child hbox10.Gtk.Box+BoxChild
			this.alignment15 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment15.Name = "alignment15";
			// Container child alignment15.Gtk.Container+ContainerChild
			this.gamePathChooserLabel = new global::Gtk.Label ();
			this.gamePathChooserLabel.Name = "gamePathChooserLabel";
			this.gamePathChooserLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Local Game Content Path:");
			this.alignment15.Add (this.gamePathChooserLabel);
			this.hbox10.Add (this.alignment15);
			global::Gtk.Box.BoxChild w40 = ((global::Gtk.Box.BoxChild)(this.hbox10 [this.alignment15]));
			w40.Position = 0;
			w40.Expand = false;
			w40.Fill = false;
			// Container child hbox10.Gtk.Box+BoxChild
			this.alignment19 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment19.Name = "alignment19";
			// Container child alignment19.Gtk.Container+ContainerChild
			this.gamePathChooser = new global::Gtk.FileChooserButton (global::Mono.Unix.Catalog.GetString ("Select a Folder"), ((global::Gtk.FileChooserAction)(2)));
			this.gamePathChooser.Name = "gamePathChooser";
			this.alignment19.Add (this.gamePathChooser);
			this.hbox10.Add (this.alignment19);
			global::Gtk.Box.BoxChild w42 = ((global::Gtk.Box.BoxChild)(this.hbox10 [this.alignment19]));
			w42.Position = 1;
			this.vbox8.Add (this.hbox10);
			global::Gtk.Box.BoxChild w43 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.hbox10]));
			w43.Position = 4;
			w43.Expand = false;
			w43.Fill = false;
			// Container child vbox8.Gtk.Box+BoxChild
			this.hbox11 = new global::Gtk.HBox ();
			this.hbox11.Name = "hbox11";
			this.hbox11.Spacing = 6;
			// Container child hbox11.Gtk.Box+BoxChild
			this.alignment16 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment16.Name = "alignment16";
			// Container child alignment16.Gtk.Container+ContainerChild
			this.label10 = new global::Gtk.Label ();
			this.label10.Name = "label10";
			this.label10.LabelProp = global::Mono.Unix.Catalog.GetString ("Game Version: ");
			this.alignment16.Add (this.label10);
			this.hbox11.Add (this.alignment16);
			global::Gtk.Box.BoxChild w45 = ((global::Gtk.Box.BoxChild)(this.hbox11 [this.alignment16]));
			w45.Position = 0;
			w45.Expand = false;
			w45.Fill = false;
			// Container child hbox11.Gtk.Box+BoxChild
			this.alignment20 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment20.Name = "alignment20";
			this.alignment20.LeftPadding = ((uint)(59));
			// Container child alignment20.Gtk.Container+ContainerChild
			this.gameVersionEntry = new global::Gtk.Entry ();
			this.gameVersionEntry.CanFocus = true;
			this.gameVersionEntry.Name = "gameVersionEntry";
			this.gameVersionEntry.Text = global::Mono.Unix.Catalog.GetString ("0.0.0");
			this.gameVersionEntry.IsEditable = true;
			this.gameVersionEntry.InvisibleChar = '●';
			this.alignment20.Add (this.gameVersionEntry);
			this.hbox11.Add (this.alignment20);
			global::Gtk.Box.BoxChild w47 = ((global::Gtk.Box.BoxChild)(this.hbox11 [this.alignment20]));
			w47.Position = 1;
			this.vbox8.Add (this.hbox11);
			global::Gtk.Box.BoxChild w48 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.hbox11]));
			w48.Position = 5;
			w48.Expand = false;
			w48.Fill = false;
			// Container child vbox8.Gtk.Box+BoxChild
			this.hbox12 = new global::Gtk.HBox ();
			this.hbox12.Name = "hbox12";
			this.hbox12.Spacing = 6;
			// Container child hbox12.Gtk.Box+BoxChild
			this.alignment17 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment17.Name = "alignment17";
			// Container child alignment17.Gtk.Container+ContainerChild
			this.label11 = new global::Gtk.Label ();
			this.label11.Name = "label11";
			this.label11.LabelProp = global::Mono.Unix.Catalog.GetString ("System Target: ");
			this.alignment17.Add (this.label11);
			this.hbox12.Add (this.alignment17);
			global::Gtk.Box.BoxChild w50 = ((global::Gtk.Box.BoxChild)(this.hbox12 [this.alignment17]));
			w50.Position = 0;
			w50.Expand = false;
			w50.Fill = false;
			// Container child hbox12.Gtk.Box+BoxChild
			this.alignment21 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment21.Name = "alignment21";
			this.alignment21.LeftPadding = ((uint)(58));
			// Container child alignment21.Gtk.Container+ContainerChild
			this.systemTargetSelector = global::Gtk.ComboBox.NewText ();
			this.systemTargetSelector.AppendText (global::Mono.Unix.Catalog.GetString ("Linux"));
			this.systemTargetSelector.AppendText (global::Mono.Unix.Catalog.GetString ("Mac"));
			this.systemTargetSelector.AppendText (global::Mono.Unix.Catalog.GetString ("Win32"));
			this.systemTargetSelector.AppendText (global::Mono.Unix.Catalog.GetString ("Win64"));
			this.systemTargetSelector.Name = "systemTargetSelector";
			this.systemTargetSelector.Active = 0;
			this.alignment21.Add (this.systemTargetSelector);
			this.hbox12.Add (this.alignment21);
			global::Gtk.Box.BoxChild w52 = ((global::Gtk.Box.BoxChild)(this.hbox12 [this.alignment21]));
			w52.Position = 1;
			this.vbox8.Add (this.hbox12);
			global::Gtk.Box.BoxChild w53 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.hbox12]));
			w53.Position = 6;
			w53.Expand = false;
			w53.Fill = false;
			this.vbox5.Add (this.vbox8);
			global::Gtk.Box.BoxChild w54 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.vbox8]));
			w54.Position = 2;
			w54.Expand = false;
			w54.Fill = false;
			w1.Add (this.vbox5);
			global::Gtk.Box.BoxChild w55 = ((global::Gtk.Box.BoxChild)(w1 [this.vbox5]));
			w55.Position = 0;
			w55.Expand = false;
			w55.Fill = false;
			// Internal child Launchpad.LauncherUtil.EditProfileDialog.ActionArea
			global::Gtk.HButtonBox w56 = this.ActionArea;
			w56.Name = "dialog1_ActionArea";
			w56.Spacing = 10;
			w56.BorderWidth = ((uint)(5));
			w56.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonCancel = new global::Gtk.Button ();
			this.buttonCancel.CanDefault = true;
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseStock = true;
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = "gtk-cancel";
			this.AddActionWidget (this.buttonCancel, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w57 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w56 [this.buttonCancel]));
			w57.Expand = false;
			w57.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button ();
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseStock = true;
			this.buttonOk.UseUnderline = true;
			this.buttonOk.Label = "gtk-ok";
			this.AddActionWidget (this.buttonOk, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w58 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w56 [this.buttonOk]));
			w58.Position = 1;
			w58.Expand = false;
			w58.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Show ();
			this.buttonCancel.Clicked += new global::System.EventHandler (this.OnButtonCancelClicked);
			this.buttonOk.Clicked += new global::System.EventHandler (this.OnButtonOkClicked);
		}
	}
}
