
// This file has been generated by the GUI designer. Do not modify.
namespace Launchpad.LauncherUtil
{
	public partial class MainWindow
	{
		private global::Gtk.UIManager UIManager;
		private global::Gtk.Action EditAction;
		private global::Gtk.Action SettingsAction;
		private global::Gtk.Action ProfilesAction;
		private global::Gtk.Action ImportProfileAction;
		private global::Gtk.Action ExportProfileAction;
		private global::Gtk.Action CreateNewProfileAction;
		private global::Gtk.Action ViewProfilesAction;
		private global::Gtk.Action EditProfileAction;
		private global::Gtk.Action ViewProfilesAction1;
		private global::Gtk.Action Action;
		private global::Gtk.Action AdvancedAction;
		private global::Gtk.Action GenerateManifestAction;
		private global::Gtk.Action GenerateFileMD5Action;
		private global::Gtk.VBox vbox1;
		private global::Gtk.MenuBar menubar1;
		private global::Gtk.Alignment alignment1;
		private global::Gtk.Label label1;
		private global::Gtk.HBox hbox1;
		private global::Gtk.Alignment alignment2;
		private global::Gtk.Button buttonGameUploadWizard;
		private global::Gtk.Alignment alignment3;
		private global::Gtk.Button button173;
		private global::Gtk.Alignment alignment4;
		private global::Gtk.Button addProfileButton;
		private global::Gtk.HBox hbox2;
		private global::Gtk.Alignment alignment5;
		private global::Gtk.Button button1;
		private global::Gtk.Alignment alignment6;
		private global::Gtk.Button button2;
		private global::Gtk.Alignment alignment7;
		private global::Gtk.Button editGameProfileButton;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Launchpad.LauncherUtil.MainWindow
			this.UIManager = new global::Gtk.UIManager ();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
			this.EditAction = new global::Gtk.Action ("EditAction", global::Mono.Unix.Catalog.GetString ("Edit"), null, null);
			this.EditAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Edit");
			w1.Add (this.EditAction, null);
			this.SettingsAction = new global::Gtk.Action ("SettingsAction", global::Mono.Unix.Catalog.GetString ("Settings"), null, null);
			this.SettingsAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Settings");
			w1.Add (this.SettingsAction, null);
			this.ProfilesAction = new global::Gtk.Action ("ProfilesAction", global::Mono.Unix.Catalog.GetString ("Profiles"), null, null);
			this.ProfilesAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Profiles");
			w1.Add (this.ProfilesAction, null);
			this.ImportProfileAction = new global::Gtk.Action ("ImportProfileAction", global::Mono.Unix.Catalog.GetString ("Import Profile"), null, null);
			this.ImportProfileAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Import Profile");
			w1.Add (this.ImportProfileAction, null);
			this.ExportProfileAction = new global::Gtk.Action ("ExportProfileAction", global::Mono.Unix.Catalog.GetString ("Export Profile"), null, null);
			this.ExportProfileAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Export Profile");
			w1.Add (this.ExportProfileAction, null);
			this.CreateNewProfileAction = new global::Gtk.Action ("CreateNewProfileAction", global::Mono.Unix.Catalog.GetString ("Create New Profile"), null, null);
			this.CreateNewProfileAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Create New Profile");
			w1.Add (this.CreateNewProfileAction, null);
			this.ViewProfilesAction = new global::Gtk.Action ("ViewProfilesAction", global::Mono.Unix.Catalog.GetString ("View Profiles"), null, null);
			this.ViewProfilesAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("View Profiles");
			w1.Add (this.ViewProfilesAction, null);
			this.EditProfileAction = new global::Gtk.Action ("EditProfileAction", global::Mono.Unix.Catalog.GetString ("Edit Profile"), null, null);
			this.EditProfileAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Edit Profile");
			w1.Add (this.EditProfileAction, null);
			this.ViewProfilesAction1 = new global::Gtk.Action ("ViewProfilesAction1", global::Mono.Unix.Catalog.GetString ("View Profiles"), null, null);
			this.ViewProfilesAction1.ShortLabel = global::Mono.Unix.Catalog.GetString ("View Profiles");
			w1.Add (this.ViewProfilesAction1, null);
			this.Action = new global::Gtk.Action ("Action", null, null, null);
			w1.Add (this.Action, null);
			this.AdvancedAction = new global::Gtk.Action ("AdvancedAction", global::Mono.Unix.Catalog.GetString ("Advanced"), null, null);
			this.AdvancedAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Advanced");
			w1.Add (this.AdvancedAction, null);
			this.GenerateManifestAction = new global::Gtk.Action ("GenerateManifestAction", global::Mono.Unix.Catalog.GetString ("Generate Manifest"), null, null);
			this.GenerateManifestAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Generate Manifest");
			w1.Add (this.GenerateManifestAction, null);
			this.GenerateFileMD5Action = new global::Gtk.Action ("GenerateFileMD5Action", global::Mono.Unix.Catalog.GetString ("Generate File MD5"), null, null);
			this.GenerateFileMD5Action.ShortLabel = global::Mono.Unix.Catalog.GetString ("Generate File MD5");
			w1.Add (this.GenerateFileMD5Action, null);
			this.UIManager.InsertActionGroup (w1, 0);
			this.AddAccelGroup (this.UIManager.AccelGroup);
			this.Name = "Launchpad.LauncherUtil.MainWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("Launchpad Utilities");
			this.Icon = global::Gdk.Pixbuf.LoadFromResource ("Launchpad.LauncherUtil.Icons8-Android-Industry-Engineering.ico");
			this.WindowPosition = ((global::Gtk.WindowPosition)(3));
			// Container child Launchpad.LauncherUtil.MainWindow.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString ("<ui><menubar name='menubar1'><menu name='EditAction' action='EditAction'><menuitem name='SettingsAction' action='SettingsAction'/></menu><menu name='ProfilesAction' action='ProfilesAction'><menuitem name='ImportProfileAction' action='ImportProfileAction'/><menuitem name='ExportProfileAction' action='ExportProfileAction'/><menuitem name='CreateNewProfileAction' action='CreateNewProfileAction'/><menuitem name='EditProfileAction' action='EditProfileAction'/><menuitem name='ViewProfilesAction1' action='ViewProfilesAction1'/></menu><menu name='Action' action='Action'/><menu name='AdvancedAction' action='AdvancedAction'><menuitem name='GenerateManifestAction' action='GenerateManifestAction'/><menuitem name='GenerateFileMD5Action' action='GenerateFileMD5Action'/></menu></menubar></ui>");
			this.menubar1 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar1")));
			this.menubar1.Name = "menubar1";
			this.vbox1.Add (this.menubar1);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.menubar1]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.alignment1 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment1.Name = "alignment1";
			// Container child alignment1.Gtk.Container+ContainerChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Welcome to Launchpad's utility collection!    Select an option below to begin.");
			this.label1.Wrap = true;
			this.label1.WidthChars = 55;
			this.alignment1.Add (this.label1);
			this.vbox1.Add (this.alignment1);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.alignment1]));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.alignment2 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment2.Name = "alignment2";
			this.alignment2.LeftPadding = ((uint)(5));
			this.alignment2.TopPadding = ((uint)(25));
			this.alignment2.BottomPadding = ((uint)(25));
			// Container child alignment2.Gtk.Container+ContainerChild
			this.buttonGameUploadWizard = new global::Gtk.Button ();
			this.buttonGameUploadWizard.CanFocus = true;
			this.buttonGameUploadWizard.Name = "buttonGameUploadWizard";
			this.buttonGameUploadWizard.UseUnderline = true;
			this.buttonGameUploadWizard.Label = global::Mono.Unix.Catalog.GetString ("Game Upload Wizard");
			this.alignment2.Add (this.buttonGameUploadWizard);
			this.hbox1.Add (this.alignment2);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.alignment2]));
			w6.Position = 0;
			// Container child hbox1.Gtk.Box+BoxChild
			this.alignment3 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment3.Name = "alignment3";
			this.alignment3.TopPadding = ((uint)(25));
			this.alignment3.BottomPadding = ((uint)(25));
			// Container child alignment3.Gtk.Container+ContainerChild
			this.button173 = new global::Gtk.Button ();
			this.button173.CanFocus = true;
			this.button173.Name = "button173";
			this.button173.UseUnderline = true;
			this.button173.Label = global::Mono.Unix.Catalog.GetString ("Launcher Upload Wizard");
			this.alignment3.Add (this.button173);
			this.hbox1.Add (this.alignment3);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.alignment3]));
			w8.Position = 1;
			// Container child hbox1.Gtk.Box+BoxChild
			this.alignment4 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment4.Name = "alignment4";
			this.alignment4.TopPadding = ((uint)(25));
			this.alignment4.RightPadding = ((uint)(5));
			this.alignment4.BottomPadding = ((uint)(25));
			// Container child alignment4.Gtk.Container+ContainerChild
			this.addProfileButton = new global::Gtk.Button ();
			this.addProfileButton.CanFocus = true;
			this.addProfileButton.Name = "addProfileButton";
			this.addProfileButton.UseUnderline = true;
			this.addProfileButton.Label = global::Mono.Unix.Catalog.GetString ("Add Game Profile");
			this.alignment4.Add (this.addProfileButton);
			this.hbox1.Add (this.alignment4);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.alignment4]));
			w10.Position = 2;
			this.vbox1.Add (this.hbox1);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
			w11.Position = 2;
			w11.Expand = false;
			w11.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.alignment5 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment5.Name = "alignment5";
			this.alignment5.LeftPadding = ((uint)(5));
			this.alignment5.BottomPadding = ((uint)(25));
			// Container child alignment5.Gtk.Container+ContainerChild
			this.button1 = new global::Gtk.Button ();
			this.button1.CanFocus = true;
			this.button1.Name = "button1";
			this.button1.UseUnderline = true;
			this.button1.Label = global::Mono.Unix.Catalog.GetString ("Game Update Wizard");
			this.alignment5.Add (this.button1);
			this.hbox2.Add (this.alignment5);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.alignment5]));
			w13.Position = 0;
			// Container child hbox2.Gtk.Box+BoxChild
			this.alignment6 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment6.Name = "alignment6";
			this.alignment6.BottomPadding = ((uint)(25));
			// Container child alignment6.Gtk.Container+ContainerChild
			this.button2 = new global::Gtk.Button ();
			this.button2.CanFocus = true;
			this.button2.Name = "button2";
			this.button2.UseUnderline = true;
			this.button2.Label = global::Mono.Unix.Catalog.GetString ("Launcher Update Wizard");
			this.alignment6.Add (this.button2);
			this.hbox2.Add (this.alignment6);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.alignment6]));
			w15.Position = 1;
			// Container child hbox2.Gtk.Box+BoxChild
			this.alignment7 = new global::Gtk.Alignment (0.5F, 0.5F, 1F, 1F);
			this.alignment7.Name = "alignment7";
			this.alignment7.RightPadding = ((uint)(5));
			this.alignment7.BottomPadding = ((uint)(25));
			// Container child alignment7.Gtk.Container+ContainerChild
			this.editGameProfileButton = new global::Gtk.Button ();
			this.editGameProfileButton.CanFocus = true;
			this.editGameProfileButton.Name = "editGameProfileButton";
			this.editGameProfileButton.UseUnderline = true;
			this.editGameProfileButton.Label = global::Mono.Unix.Catalog.GetString ("Edit Game Profile");
			this.alignment7.Add (this.editGameProfileButton);
			this.hbox2.Add (this.alignment7);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.alignment7]));
			w17.Position = 2;
			this.vbox1.Add (this.hbox2);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox2]));
			w18.Position = 3;
			w18.Expand = false;
			w18.Fill = false;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 490;
			this.DefaultHeight = 244;
			this.Show ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
			this.ImportProfileAction.Activated += new global::System.EventHandler (this.OnImportProfileActionActivated);
			this.ExportProfileAction.Activated += new global::System.EventHandler (this.OnExportProfileActionActivated);
			this.CreateNewProfileAction.Activated += new global::System.EventHandler (this.OnCreateNewProfileActionActivated);
			this.EditProfileAction.Activated += new global::System.EventHandler (this.OnEditProfileActionActivated);
			this.ViewProfilesAction1.Activated += new global::System.EventHandler (this.OnViewProfilesAction1Activated);
			this.GenerateManifestAction.Activated += new global::System.EventHandler (this.OnGenerateManifestActionActivated);
			this.GenerateFileMD5Action.Activated += new global::System.EventHandler (this.OnGenerateFileMD5ActionActivated);
			this.buttonGameUploadWizard.Clicked += new global::System.EventHandler (this.OnButtonGameUploadWizardClicked);
			this.addProfileButton.Clicked += new global::System.EventHandler (this.OnAddProfileButtonClicked);
			this.editGameProfileButton.Clicked += new global::System.EventHandler (this.OnEditGameProfileButtonClicked);
		}
	}
}
