
// This file has been generated by the GUI designer. Do not modify.
namespace Launchpad.LauncherUtil
{
	public partial class GameUploadWidget_Files
	{
		private global::Gtk.VBox vbox4;
		private global::Gtk.Button button365;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Launchpad.LauncherUtil.GameUploadWidget_Files
			global::Stetic.BinContainer.Attach (this);
			this.Name = "Launchpad.LauncherUtil.GameUploadWidget_Files";
			// Container child Launchpad.LauncherUtil.GameUploadWidget_Files.Gtk.Container+ContainerChild
			this.vbox4 = new global::Gtk.VBox ();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.button365 = new global::Gtk.Button ();
			this.button365.CanFocus = true;
			this.button365.Name = "button365";
			this.button365.UseUnderline = true;
			this.button365.Label = global::Mono.Unix.Catalog.GetString ("Files");
			this.vbox4.Add (this.button365);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.button365]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			this.Add (this.vbox4);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
